chaibuilder/sdk

src/core/components/sidepanels/panels/outline/arborist/ListTree.tsx

I fixed the **context menu** using target.closest. It works fine. Also, I implemented **CanDropBlock** in Node as well as the Tree prop. I didn't remove the children.length feature, as it was used in having a conditional behind the right arrow button.
https://github.com/chaibuilder/sdk/assets/83443927/5267c9fe-9a27-44c0-92b0-2d2fd82ebcf3

Fixed the Context Menu and Implemented CanDropBlock

---

src/core/components/settings/new-panel/ManualClasses.tsx

Here how it looks like after fix:

fix: fixed the ui break on adding long classes

---

src/core/components/settings/new-panel/ManualClasses.tsx
src/core/components/sidepanels/panels/images/ImagesPanel.tsx
src/core/functions/Blocks.ts
src/core/functions/split-blocks.ts
src/ui/widgets/rjsf/widgets/image.tsx

This PR addresses an issue in the `nestedToFlatArray` function within `Blocks.ts`, where the `parent` was added to the new blocks being created due to which `_parent` and `parent` are found twice. The fix involves changing the `parent` to `_parent: parent` in the object spread, ensuring it's only added once.
- In `Blocks.ts`, specifically within the `nestedToFlatArray` function, modified the object spread that creates new blocks to prevent the `_parent` key from being added twice.
- This change ensures the integrity of the data structure by preventing duplicate keys, which could potentially lead to confusion or errors in downstream processes that consume these blocks.
- It simplifies the object structure, making it more predictable and easier to understand.
- There should be no adverse …

FIx: _parent key is added twice. Need to remove "parent" key

---

src/core/components/canvas/dnd/useDnd.ts
src/core/components/sidepanels/panels/outline/treeview/ListTree.tsx

**Description:**
This PR introduces the following enhancements to the outline drag-and-drop functionality:
1. **Collapse the Dragged Node on Drag:**
- When a node is dragged in the outline, it will automatically collapse. This helps in reducing visual clutter and makes it easier to identify the drop target.
2. **Highlight Drop Target on Canvas:**
- While dragging a block in the outline, the corresponding drop target on the canvas will be highlighted. This provides a clear visual indication of where the block can be dropped, improving the user experience.
**Changes Made:**
- Updated the [`Node`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22d%3A%5C%5Csdk%5C%5Csrc%5C%5Ccore%5C%5Ccomponents%5C%5Csidepanels%5C%5Cpanels%5C …

Feat: On drag in outline, collapse the dragged node on drag and highlight the drop target on canvas

---

src/core/components/layout/RootLayout.tsx
src/core/components/sidepanels/panels/theme-configuration/BorderRadiusInput.tsx
src/core/components/sidepanels/panels/theme-configuration/ThemeConfigPanel.tsx

Fixed the following :
1. Border radius slider not working correctly in theme settings
2. Change the icon of theme settings to one same as topbar
3. Handle dark mode theming based on canvas dark mode instead of switch for colors

fix: fixed inconsistent border Radius and Icon for theme

---

src/core/components/canvas/topbar/Breakpoints.tsx

We had a few Design related requirements that weren't currently supported by the Breakpoints component, so I added the ability to put custom default classes for the components icon container, the components listing container, and the component's selected state. Please Review @surajair

feat: ability to customize breakpoints component style

---

src/core/components/canvas/topbar/UndoRedo.tsx

Similar to the last pull request, added props to the undoredo component that allow changing it's native styles, making it easier for users to attend it's own builders design specifications. 
link to the last PR...
https://github.com/chaibuilder/sdk/pull/78

feat: undoredo component style is now changeable through props

---

src/web-blocks/form/select.tsx

I have removed the "dangerouslySetInnerHtml" and instead used simple <option>. I think we don't need this. Since we are only using label for that.
Fix: Used optional chaining to fix the undefined errors.

fix: fixed the canvas breaking due to undefined values

---

src/core/hooks/useKeyEventWatcher.ts

- used ```preventDefault: true``` to remove Browser default Behaviour for pasting.

fix: fixed twice paste on key press

---

src/web-blocks/form/form.tsx

I might not be seeing the whole picture somehow, but it seems to me as if the form functionality just wasn't finished. When alpinejs was not loaded on the webpage, the form would simply redirect the user to the URL configured in the form. When alpinejs was loaded on the page, it would work as shown below: with some data and things not being able to be used by alpinejs because they weren't even created in the first place. 
The error and success messages also were not working. Now they are.

feat: finish implementation of form alpine js attributes

---

src/core/components/layout/RootLayout.tsx
src/web-blocks/form/label.tsx

Issue: 
- Due to not occupy entire width by header back content was visible
- But in outline case there is absolute position element out of container for that case added condition, in this case tree component inbuild doesn't allow to show overflow data
Issue images:

feat: add internal panel flag and improve sidebar header styling

---

.github/workflows/release.yml
package.json

Fixes #184
Add GitHub Action workflow to release package to npm on tag creation.
* **New GitHub Action Workflow**: Create `.github/workflows/release.yml` to trigger on tag creation matching `v-*.*.*`.
* Checkout repository using `actions/checkout@v3`.
* Set up Node.js using `actions/setup-node@v3` with `node-version: 18`.
* Install dependencies using `npm install -g pnpm && pnpm install --no-frozen-lockfile`.
* Build the project using `pnpm run build`.
* Publish the package to npm using `npm publish` with `NPM_TOKEN` from repository secrets.
* **package.json**: Add `publish` script to `scripts` section to publish the package to npm.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/chaibuilder/sdk/pull/185?shareId=fd42a952-87e1-4190-ab25-c7 …

Configure GitHub Actions to release the package to npm registry on creating a specific tag

---

src/core/components/index.ts
src/core/components/settings/JSONForm.tsx
src/core/components/settings/JSONFormFieldTemplate.tsx

If a user wants to implement a custom field template for a specific input, they previously had to rewrite the entire custom template and pass it to the editor. However, now users can create a custom field template, return the `JSONFormFieldTemplate` within it, and apply conditional customizations to the field template

Separate and export the JSONForm custom field template

---

src/core/components/sidepanels/panels/add-blocks/UILibrariesPanel.tsx

refactor: simplify UILibrariesPanel by removing unused registeredBlocks

---

package.json
pnpm-lock.yaml
src/Preview.tsx
src/_demo/blocks/CollectionList.tsx
src/core/components/sidepanels/panels/add-blocks/libraries-panel.tsx
src/core/lib.ts
src/render/async-props-block.tsx
src/render/get-tailwind-css.ts
src/render/index.ts
src/render/render-chai-blocks.tsx

New:
- Added `forwardProps` to send additional props to all blocks rendered using Chai Builder.
- Changed the api signature of data providers

feat: improved render-chai-block apis and data providers

---

src/_demo/panels/panel.tsx
src/core/components/layout/root-layout.tsx
src/core/extensions/save-to-library.tsx

This PR passes a close() prop to components registered with `registerSidebarPanel()`. THis should allow user to close the dialog programatically after performing certain actions. eg: submitting a form

feat: added close() props to sidepanels 

---

src/web-blocks/repeater.tsx

Add a loading skeleton and a "none" tag option to the Repeater component in the web-blocks directory.
The "none" tag allows users to render items conditionally without a wrapper element, which is useful in certain scenarios. The loading skeleton is added to improve the user experience by providing visual feedback when content is loading in the builder environment.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`

feat: add loading skeleton and none tag option to repeater component

---

src/Editor.tsx
src/core/components/canvas/IframeInitialContent.ts
src/core/components/canvas/static/new-blocks-renderer.tsx
src/types/chaibuilder-editor-props.ts

Add double-click navigation to partial blocks with overlay UI and update related components and props.
This change allows users to easily navigate to and edit partial blocks within the editor by double-clicking on them, provided there are no unsaved changes. This improves the user experience by introducing an intuitive interaction method for accessing partial block details, and the overlay UI provides visual feedback. The modifications ensure that navigation respects the current language settings and only proceeds with saved content, reducing errors and enhancing usability.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`

feat: add double-click navigation to partial blocks with overlay UI

---

src/core/hooks/use-copy-blockIds.ts
src/core/hooks/use-key-event-watcher.ts

🐞 Issue
Block copy was being triggered even when only text was selected, causing unexpected behavior on Ctrl+C / Cmd+C.
✅ Fix
Enabled hotkeys (copy, paste, duplicate) only when block IDs are present.
Added missing callback dependencies to ensure stable references in useHotkeys.
Now, text selection and copy work normally, and block actions trigger only when intended.
Prevent the block copy action from being triggered during a text selection by checking for empty block IDs and updating the keyboard shortcut handler to disable when no blocks are selected.
Previously, pressing Ctrl+C/Cmd+C initiated the block copy functionality even when only text was selected, causing confusion and unexpected behavior. The change ensures the event listener only activates when there are block IDs to copy, …

bug: Block copy was being triggered even when only text was selected, causing unexpected behavior on Ctrl+C / Cmd+C.

---

src/core/rjsf-widgets/json-form-field-template.tsx

fix(removed extra description): add tooltip for schema description in JSONFormFieldTemplate

---

src/core/hooks/use-is-page-loaded.ts
src/core/hooks/use-save-page.ts

Update the `useIsPageLoaded` hook to return the correct state, ensuring proper usage in other components.

Fix useIsPageLoaded hook to return state correctly
