package.json
pnpm-lock.yaml
src/RJSF.tsx
src/core/components/settings/BlockSettings.tsx
src/core/components/settings/Settings.tsx
src/main.tsx
src/studio/components/add-page-modal.tsx
src/ui/widgets/rjsf/widgets/data-binding.tsx
src/ui/widgets/rjsf/widgets/link.tsx

Fixed:
- https://github.com/chaibuilder/sdk/issues/4

fix: issue #4: SDK freezing on selecting Link or Button from Blocks

---

package.json
pnpm-lock.yaml
src/core/atoms/ui.ts
src/core/components/canvas/IframeInitialContent.ts
src/core/components/canvas/KeyboarHandler.tsx
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/canvas/static/Canvas.tsx
src/core/hooks/useUpdateBlocksProps.ts

- Added support for inline content editing

Inline editing support

---

package.json
pnpm-lock.yaml
src/blocks/CustomBlock.tsx
src/core/FEATURE_TOGGLES.tsx
src/core/atoms/ui.ts
src/core/components/canvas/EmptyCanvas.tsx
src/core/components/canvas/IframeInitialContent.ts
src/core/components/canvas/dnd/useDnd.ts
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/canvas/static/Canvas.tsx
src/core/components/canvas/static/StaticBlocksRenderer.tsx
src/core/components/canvas/static/StaticCanvas.tsx
src/core/components/sidepanels/SidePanels.tsx
src/core/components/sidepanels/panels/add-blocks/AddBlocks.tsx
src/core/components/sidepanels/panels/add-blocks/CoreBlock.tsx
src/core/components/sidepanels/panels/add-blocks/ImportHTML.tsx
src/core/components/sidepanels/panels/add-blocks/PredefinedBlocks.tsx
src/core/components/sidepanels/panels/layers/Layers.tsx
src/core/functions/InsertBlockAtIndex.test.ts
src/core/functions/InsertBlockAtIndex.ts
src/core/hooks/useAddBlockByDrop.ts

- Add support for drag and drop on canvas ( WIP )
- Behind a feature flag

Feature: Drag and Drop support on Canvas (WIP)

---

package.json
src/core/FEATURE_TOGGLES.tsx
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/canvas/static/Canvas.tsx
src/core/components/settings/BlockSettings.tsx
src/core/components/sidepanels/SidePanels.tsx
src/core/main/ChaiBuilderEditor.tsx
src/core/types/chaiBuilderEditorProps.ts
src/index.css

1. feat: control dnd feature toggle via query string
2. feat: added data providers as optional support via builder prop
3. fix: handled inline editing when spacing is added by parent
4. refactor: moved highlighting logic to canvas from block

Usability improvements

---

jest.config.cjs
package.json
pnpm-lock.yaml

Fixed failing unit test cases due to esm module (lodash-es)

FIX: failing unit test cases

---

pnpm-lock.yaml
src/core/components/sidepanels/panels/outline/arborist/ListTree.tsx
src/core/components/sidepanels/panels/outline/react-dnd-treeview/Outline.tsx

https://github.com/chaibuilder/sdk/assets/83443927/3c8588c9-d526-4765-ae8e-725670046a7f
-  Fixed the additional blocks as children by removing duplicates.
-  Shown icons as per old design.
-  Handled the hover state of every node in the tree.
-  Handled the selection color of every node in the tree.
-  Clicking on Canvas the tree should highlight the selected block. 
_**There seems to be some issue related to the selection of the block on canvas that highlights the same in the tree. WIll look into that.**_

Features related to React-arborist

---

src/core/components/canvas/IframeInitialContent.ts
src/core/components/canvas/dnd/useDnd.ts
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/sidepanels/panels/add-blocks/UILibrariesPanel.tsx

- **Feature**: Added opacity to the dragged element to improve user experience during drag-and-drop operations.
- **Bug Fix**: Resolved the issue where elements could be dropped onto themselves, preventing unintended behavior.
- **Opacity Adjustment**: The dragged element now has a reduced opacity, making it clear which element is being moved.
- **Self-Drop Fix**: Implemented a check to ensure that an element cannot be dropped onto itself, thus avoiding potential errors and confusion.
- Verified that the dragged element's opacity changes as expected during drag-and-drop.
- Confirmed that elements cannot be dropped onto themselves.

feat: added opacity to dragged Element and fixed the self-drop issue

---

package.json
src/core/components/AskAi.tsx
src/core/components/canvas/topbar/Breakpoints.tsx
src/core/components/settings/SettingsPanel.tsx
src/core/components/sidepanels/SidePanels.tsx
src/core/components/sidepanels/panels/outline/treeview/ListTree.tsx
src/core/main/index.ts

Added:
1- UILibraries
2- AISetContext
3- AIUserPrompt

feat: added more components to core sdk

---

package.json
src/core/atoms/builder.ts
src/core/components/canvas/Breadcrumb.tsx
src/core/components/canvas/CanvasArea.tsx
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/canvas/static/Canvas.tsx
src/core/components/canvas/static/HeadTags.tsx
src/core/components/canvas/static/ResizableCanvasWrapper.tsx
src/core/components/layout/ChooseLayout.tsx
src/core/components/layout/RootLayout.tsx
src/core/components/sidepanels/panels/images/ImagePickerModal.tsx
src/core/components/sidepanels/panels/images/UnsplashImages.tsx
src/core/components/sidepanels/panels/images/UploadImages.tsx
src/core/components/sidepanels/panels/outline/treeview/ListTree.tsx
src/core/constants/LAYOUT_MODE.ts
src/core/hooks/useHiddenBlocks.ts
src/core/hooks/useLayoutVariant.ts
src/core/hooks/useSelectedBlockIds.ts
src/core/rjsf-widgets/Code.tsx
src/core/rjsf-widgets/Icon.tsx
src/core/types/chaiBuilderEditorProps.ts

User can now hide blocks inside builder

feature: hidden blocks & breadcrumb support added

---

src/core/components/canvas/Breadcrumb.tsx
src/core/components/canvas/static/Canvas.tsx
src/core/components/canvas/static/HeadTags.tsx
src/core/components/sidepanels/panels/add-blocks/CoreBlock.tsx
src/core/components/sidepanels/panels/add-blocks/UILibrariesPanel.tsx
src/core/components/sidepanels/panels/outline/treeview/ListTree.tsx
src/core/components/sidepanels/panels/outline/treeview/TreeActionTooltips.tsx
src/core/hooks/index.ts
src/core/hooks/useBlockHighlight.ts
src/core/hooks/useBuilderReset.ts

- Optimized script execution time from ~10.7s to ~0.5s
- Reduced total page load time from 12.7s to 7.6s
- Scripting: 10,754 ms
- Total load time: 12,716 ms
- High number of synchronous tasks blocking the main thread
- Scripting: 543 ms
- Total load time: 7,596 ms
- Better task distribution and reduced main thread blocking
- 95% reduction in script execution time
- 40% improvement in overall page load time
- Smoother animations and better user experience
- Reduced CPU utilization
Before: 
After:
Verified using Chrome DevTools Performance profiler in a controlled environment.

Performance Optimization: Reduced Script Execution Time by 95%

---

src/core/components/settings/new-panel/ManualClasses.tsx
src/web-blocks/global-block.tsx
src/web-blocks/link.tsx

✅ Fixed global block to be a hidden widget
✅ Reduced font size of autosuggest classes
✅ Fixed duplicate link title issue

Global-hidden-fix

---

src/web-blocks/heading.tsx

1. Changed the incorrect "level" to "tag" prop.

Heading-fix

---

package.json
src/core/components/canvas/BlockFloatingActions.tsx
src/core/components/canvas/BlockStyleHighlight.tsx
src/core/components/canvas/IframeInitialContent.ts
src/core/components/canvas/static/HeadTags.tsx
src/core/components/canvas/static/RuntimePropsBlock.tsx
src/core/components/canvas/static/StaticCanvas.tsx
src/core/components/settings/BlockStyling.tsx
src/core/components/settings/BlockStylingProps.tsx
src/core/components/settings/JSONForm.tsx
src/core/components/settings/new-panel/ManualClasses.tsx
src/core/components/sidepanels/panels/theme-configuration/FontSelector.tsx
src/core/hooks/useTheme.ts
src/render/RenderChaiBlocks.tsx

feat: added option to choose multiple styling element inside the selected block

---

src/core/components/settings/BlockSettings.tsx
src/core/hooks/index.ts
src/core/hooks/useSelectedBlockIds.ts
src/core/hooks/useWrapperBlock.ts
src/web-blocks/dropdown-menu.tsx

Added settings of parent with wrapper in child block settings for quick access

---

src/__dev/ptBR.json
src/core/components/sidepanels/panels/add-blocks/AddBlocks.tsx
src/core/components/sidepanels/panels/add-blocks/ChaiDraggableBlock.tsx

- added add block translation keys
- removed accordion from add block panel

feat: added translation and removed unused accordion

---

src/Editor.tsx
src/Preview.tsx
src/__dev/LangButton.tsx
src/core/components/NestedPathSelector.tsx
src/core/components/canvas/static/BlocksRenderer.tsx
src/core/components/settings/new-panel/ManualClasses.tsx
src/core/hooks/getSplitClasses.ts
src/core/hooks/useAddClassesToBlocks.ts
src/core/hooks/useAskAi.ts
src/core/hooks/useRemoveClassesFromBlocks.ts
src/core/hooks/useSelectBlockClasses.ts
src/core/import-html/general.ts
src/render/RenderChaiBlocks.tsx
src/render/functions.ts
src/web-blocks/dropdown-menu.tsx

- Handled classes with commas inside the arbitrary classes
- Dropdown menu to have i18n and ai props
-

Mutliple bug fixes

---

src/core/components/sidepanels/panels/outline/TypeIcon.tsx

https://github.com/chaibuilder/sdk/issues/195

refactor: dynamically render block type icons using registered chai blocks

---

src/core/import-html/html-to-json.ts

https://github.com/chaibuilder/sdk/issues/197

feat: add form action attribute mapping in HTML import

---

src/Editor.tsx
src/core/components/canvas/AddBlockDropdown.tsx
src/core/components/canvas/BlockFloatingActions.tsx
src/core/components/canvas/static/AddBlockAtBottom.tsx
src/core/components/canvas/topbar/AiAssistant.tsx
src/core/components/settings/SettingsPanel.tsx
src/core/components/sidepanels/panels/add-blocks/AddBlocks.tsx
src/core/components/sidepanels/panels/outline/treeview/BlockContextMenu.tsx
src/core/components/sidepanels/panels/outline/treeview/ListTree.tsx
src/core/components/sidepanels/panels/theme-configuration/ThemeConfigPanel.tsx
src/core/constants/PERMISSIONS.ts
src/core/hooks/index.ts
src/core/hooks/usePermissions.ts
src/core/hooks/useRemoveBlocks.ts
src/core/hooks/useSavePage.ts
src/core/main/index.ts
src/core/types/chaiBuilderEditorProps.ts

Handled permissions:
```
export const PERMISSIONS = {
ADD_BLOCK: "add_block",
DELETE_BLOCK: "delete_block",
EDIT_BLOCK: "edit_block",
MOVE_BLOCK: "move_block",
EDIT_THEME: "edit_theme",
SAVE_PAGE: "save_page",
EDIT_STYLES: "edit_styles",
IMPORT_HTML: "import_html",
};
```

Added permissions to builder.

---

src/core/components/canvas/static/chai-theme-helpers.ts
src/core/components/canvas/static/head-tags.tsx
src/core/components/chaibuilder-editor.tsx
src/core/components/css-theme-var.tsx

This should help the user feel more inine with their brand color

feat: use sites primary colors as primary color for builder

---

src/core/components/sidepanels/panels/add-blocks/libraries-panel.tsx

feat: add description to BlockCard and improve layout in library for missing preview image

---

src/core/components/sidepanels/panels/add-blocks/libraries-panel.tsx

Added ability to search the library blocks using name and description.
Implemented using fuzzy seach for better results.

feat: implement search functionality in UILibrarySection with Fuse.js integration

---

src/Preview.tsx
src/_demo/THEME_PRESETS.ts
src/core/components/canvas/block-floating-actions.tsx
src/core/components/canvas/canvas-area.tsx
src/core/components/canvas/static/chai-theme-helpers.ts
src/core/components/canvas/static/head-tags.tsx
src/core/components/canvas/static/static-canvas.tsx
src/core/components/chaibuilder-editor.tsx
src/core/components/css-theme-var.tsx
src/core/components/index.ts
src/core/components/layout/root-layout.tsx
src/core/hooks/defaultThemeOptions.ts
src/core/hooks/useTheme.ts
src/core/main/index.ts
src/types/chaibuilder-editor-props.ts

added an optional prop for builder shadcn theme

feat: added support for shadcn theme for builder

---

src/core/components/sidepanels/panels/images/media-manager-modal.tsx
src/core/extensions/media-manager.tsx
src/core/rjsf-widgets/image.tsx
src/types/index.ts
src/web-blocks/image.tsx

- image block can now maintain the reference to asset id coming from DAM
- Image src can be cleared from settings panel

feat: improvements added to media manager 

---

src/core/components/settings/new-panel/manual-classes.tsx

This feat allows user to edit an existing classes by double clicking in the styles panel

feat: allow editing classes by double clicking

---

src/core/history/use-undo-manager.ts

fix(undo): undo redo not working correctly

---

src/Preview.tsx
src/render/apply-binding.ts
src/render/block-renderer.tsx
src/render/blocks-renderer.tsx
src/web-blocks/repeater.tsx

feat(live): handling collection data binding in live rendering of blocks

---

src/Editor.tsx
src/core/components/canvas/static/new-blocks-renderer.tsx
src/core/components/settings/json-form.tsx
src/core/rjsf-widgets/repeater-binding.tsx
src/web-blocks/repeater.tsx

- Custom RJSF widget for repeater data binding
- Placeholder when no Repeater items
- Update text from 'Items' to 'Collection'
- Update text from 'No items found' to 'Choose a data binding...'

Custom RJSF widget for repeater data binding

---

src/web-blocks/button.tsx
src/web-blocks/link.tsx

Add a `prefetchLink` option to the button and link components for improved performance.
These changes introduce an optional `prefetchLink` feature to optimize loading behavior by allowing users to prefetch link resources, enhancing overall application performance. This boolean configuration option defaults to `false` to maintain current functionality and provide flexibility for developers to enable it as needed.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`

feat: add prefetchLink option to button and link components for improved performance

---

src/core/rjsf-widgets/image.tsx

[Screencast from 2025-08-11 14-14-58.webm](https://github.com/user-attachments/assets/8e4ea8e6-b032-4d72-97a9-4e81da815144)

fix(image manager) : fixed some UI behaviour 

---

src/core/components/canvas/static/apply-language.test.ts
src/core/components/canvas/static/new-blocks-render-helpers.ts

Enhance the language application logic by trimming values and adding type checks to ensure proper handling of selected languages.

Improve language application logic with trimming and type checks

---

src/core/components/ask-ai-panel.tsx

fix(ui-tweak): simplify AIUserPrompt component by removing toggle functionality and unused state

---

src/Editor.tsx
src/_demo/panels/panel.tsx
src/core/components/layout/root-layout.tsx
src/extentions.tsx

feat: reverse bottom panel order
